"""Phase 1 catalog, sales, payments, ledger, and corrections."""
from alembic import op
import sqlalchemy as sa

revision = "0002_phase1_sales"
down_revision = "0001_phase0_foundation"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("product_categories", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(50), nullable=False, unique=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("icon", sa.String(16)), sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("is_demo", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_table("discount_rules", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(80), nullable=False), sa.Column("basis_points", sa.Integer(), nullable=False, unique=True), sa.Column("requires_approval", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.CheckConstraint("basis_points >= 0 AND basis_points <= 10000", name="ck_discount_basis_points"))
    op.create_table("products", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("category_id", sa.Integer(), sa.ForeignKey("product_categories.id", ondelete="RESTRICT"), nullable=False), sa.Column("code", sa.String(60), nullable=False, unique=True), sa.Column("name", sa.String(160), nullable=False), sa.Column("pricing_mode", sa.String(24), nullable=False), sa.Column("fixed_price_minor", sa.BigInteger()), sa.Column("fixed_price_currency", sa.String(3)), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("is_demo", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("pricing_mode IN ('FIXED_PRICE','OPEN_PRICE')", name="ck_product_pricing_mode"), sa.CheckConstraint("fixed_price_minor IS NULL OR fixed_price_minor > 0", name="ck_product_price_positive"), sa.CheckConstraint("fixed_price_currency IS NULL OR fixed_price_currency IN ('KHR','USD')", name="ck_product_currency"), sa.CheckConstraint("(pricing_mode = 'FIXED_PRICE' AND fixed_price_minor IS NOT NULL AND fixed_price_currency IS NOT NULL) OR (pricing_mode = 'OPEN_PRICE' AND fixed_price_minor IS NULL AND fixed_price_currency IS NULL)", name="ck_product_price_by_mode"))
    op.create_table("product_suggested_prices", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("product_id", sa.Integer(), sa.ForeignKey("products.id", ondelete="RESTRICT"), nullable=False), sa.Column("amount_minor", sa.BigInteger(), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.CheckConstraint("amount_minor > 0", name="ck_suggested_price_positive"), sa.CheckConstraint("currency IN ('KHR','USD')", name="ck_suggested_price_currency"), sa.UniqueConstraint("product_id", "amount_minor", "currency", name="uq_product_suggested_price"))
    op.create_table("sales", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("receipt_number", sa.String(40), nullable=False, unique=True), sa.Column("business_day_id", sa.Integer(), sa.ForeignKey("business_days.id", ondelete="RESTRICT"), nullable=False), sa.Column("staff_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("status", sa.String(16), nullable=False, server_default="POSTED"), sa.Column("currency", sa.String(3), nullable=False), sa.Column("subtotal_minor", sa.BigInteger(), nullable=False), sa.Column("discount_basis_points", sa.Integer(), nullable=False, server_default="0"), sa.Column("discount_minor", sa.BigInteger(), nullable=False, server_default="0"), sa.Column("total_minor", sa.BigInteger(), nullable=False), sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False), sa.Column("reversed_at", sa.DateTime(timezone=True)), sa.Column("reversed_by_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="RESTRICT")), sa.Column("reversal_reason", sa.Text()), sa.CheckConstraint("status IN ('POSTED','REVERSED')", name="ck_sale_status"), sa.CheckConstraint("currency IN ('KHR','USD')", name="ck_sale_currency"), sa.CheckConstraint("subtotal_minor > 0 AND discount_minor >= 0 AND total_minor > 0", name="ck_sale_amounts_positive"), sa.CheckConstraint("subtotal_minor - discount_minor = total_minor", name="ck_sale_total_math"), sa.CheckConstraint("discount_basis_points >= 0 AND discount_basis_points <= 10000", name="ck_sale_discount_basis_points"))
    op.create_table("sale_items", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("sale_id", sa.Integer(), sa.ForeignKey("sales.id", ondelete="RESTRICT"), nullable=False), sa.Column("product_id", sa.Integer(), sa.ForeignKey("products.id", ondelete="RESTRICT")), sa.Column("product_code_snapshot", sa.String(60)), sa.Column("name_snapshot", sa.String(160), nullable=False), sa.Column("pricing_mode_snapshot", sa.String(24), nullable=False), sa.Column("quantity", sa.Integer(), nullable=False), sa.Column("unit_price_minor", sa.BigInteger(), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("line_total_minor", sa.BigInteger(), nullable=False), sa.CheckConstraint("pricing_mode_snapshot IN ('FIXED_PRICE','OPEN_PRICE','MANUAL_ITEM')", name="ck_sale_item_pricing_mode"), sa.CheckConstraint("quantity > 0 AND unit_price_minor > 0 AND line_total_minor > 0", name="ck_sale_item_amounts"), sa.CheckConstraint("line_total_minor = quantity * unit_price_minor", name="ck_sale_item_math"), sa.CheckConstraint("currency IN ('KHR','USD')", name="ck_sale_item_currency"))
    op.create_table("sale_payments", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("sale_id", sa.Integer(), sa.ForeignKey("sales.id", ondelete="RESTRICT"), nullable=False), sa.Column("method", sa.String(20), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("amount_minor", sa.BigInteger(), nullable=False), sa.Column("is_reversal", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("reverses_payment_id", sa.Integer(), sa.ForeignKey("sale_payments.id", ondelete="RESTRICT")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("method IN ('CASH','ABA_KHQR')", name="ck_sale_payment_method"), sa.CheckConstraint("currency IN ('KHR','USD')", name="ck_sale_payment_currency"), sa.CheckConstraint("amount_minor > 0", name="ck_sale_payment_amount"))
    op.create_table("ledger_entries", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_day_id", sa.Integer(), sa.ForeignKey("business_days.id", ondelete="RESTRICT"), nullable=False), sa.Column("entry_type", sa.String(40), nullable=False), sa.Column("direction", sa.String(12), nullable=False), sa.Column("amount_minor", sa.BigInteger(), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("payment_method", sa.String(20), nullable=False), sa.Column("source_entity_type", sa.String(40), nullable=False), sa.Column("source_entity_id", sa.String(80), nullable=False), sa.Column("actor_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("reverses_ledger_entry_id", sa.Integer(), sa.ForeignKey("ledger_entries.id", ondelete="RESTRICT")), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("direction IN ('INFLOW','OUTFLOW')", name="ck_ledger_direction"), sa.CheckConstraint("amount_minor > 0", name="ck_ledger_amount"), sa.CheckConstraint("currency IN ('KHR','USD')", name="ck_ledger_currency"), sa.CheckConstraint("payment_method IN ('CASH','ABA_KHQR')", name="ck_ledger_payment_method"))
    op.create_index("ix_ledger_business_day_currency", "ledger_entries", ["business_day_id", "currency"])
    op.create_table("sale_corrections", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("original_sale_id", sa.Integer(), sa.ForeignKey("sales.id", ondelete="RESTRICT"), nullable=False, unique=True), sa.Column("replacement_sale_id", sa.Integer(), sa.ForeignKey("sales.id", ondelete="RESTRICT")), sa.Column("reason", sa.Text(), nullable=False), sa.Column("actor_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))


def downgrade() -> None:
    op.drop_table("sale_corrections")
    op.drop_index("ix_ledger_business_day_currency", table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_table("sale_payments")
    op.drop_table("sale_items")
    op.drop_table("sales")
    op.drop_table("product_suggested_prices")
    op.drop_table("products")
    op.drop_table("discount_rules")
    op.drop_table("product_categories")

