"""Phase 2 expenses, limits, attachments, approvals, and notifications."""
from alembic import op
import sqlalchemy as sa

revision = "0003_phase2_expenses"
down_revision = "0002_phase1_sales"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("expense_categories", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(60), nullable=False, unique=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("icon", sa.String(16)), sa.Column("receipt_required", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"))
    op.create_table("expense_limits", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("role_id", sa.Integer(), sa.ForeignKey("roles.id", ondelete="RESTRICT")), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="RESTRICT")), sa.Column("currency", sa.String(3), nullable=False), sa.Column("amount_minor", sa.BigInteger(), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_by_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="RESTRICT")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("currency IN ('KHR','USD')", name="ck_expense_limit_currency"), sa.CheckConstraint("amount_minor >= 0", name="ck_expense_limit_amount"), sa.CheckConstraint("(role_id IS NOT NULL AND user_id IS NULL) OR (role_id IS NULL AND user_id IS NOT NULL)", name="ck_expense_limit_scope"), sa.UniqueConstraint("role_id", "currency", name="uq_expense_limit_role_currency"), sa.UniqueConstraint("user_id", "currency", name="uq_expense_limit_user_currency"))
    op.create_table("expense_requests", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("request_number", sa.String(40), nullable=False, unique=True), sa.Column("business_day_id", sa.Integer(), sa.ForeignKey("business_days.id", ondelete="RESTRICT"), nullable=False), sa.Column("requester_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("category_id", sa.Integer(), sa.ForeignKey("expense_categories.id", ondelete="RESTRICT"), nullable=False), sa.Column("amount_minor", sa.BigInteger(), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("payment_source", sa.String(20), nullable=False), sa.Column("reason", sa.Text(), nullable=False), sa.Column("status", sa.String(16), nullable=False, server_default="PENDING"), sa.Column("authority_limit_minor", sa.BigInteger()), sa.Column("was_over_limit", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("receipt_required_snapshot", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False), sa.Column("decided_at", sa.DateTime(timezone=True)), sa.Column("decided_by_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="RESTRICT")), sa.Column("decision_reason", sa.Text()), sa.CheckConstraint("amount_minor > 0", name="ck_expense_request_amount"), sa.CheckConstraint("currency IN ('KHR','USD')", name="ck_expense_request_currency"), sa.CheckConstraint("payment_source IN ('KHR_CASH','USD_CASH','ABA_KHQR')", name="ck_expense_request_source"), sa.CheckConstraint("status IN ('PENDING','APPROVED','REJECTED')", name="ck_expense_request_status"), sa.CheckConstraint("authority_limit_minor IS NULL OR authority_limit_minor >= 0", name="ck_expense_request_limit"))
    op.create_table("expense_attachments", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("expense_request_id", sa.Integer(), sa.ForeignKey("expense_requests.id", ondelete="RESTRICT"), nullable=False), sa.Column("telegram_file_id", sa.String(255), nullable=False), sa.Column("telegram_file_unique_id", sa.String(255)), sa.Column("media_type", sa.String(20), nullable=False), sa.Column("mime_type", sa.String(100)), sa.Column("file_size", sa.BigInteger()), sa.Column("local_relative_path", sa.String(255)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("media_type IN ('PHOTO','DOCUMENT')", name="ck_expense_attachment_media_type"), sa.CheckConstraint("file_size IS NULL OR file_size >= 0", name="ck_expense_attachment_size"))
    op.create_table("expense_approval_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("expense_request_id", sa.Integer(), sa.ForeignKey("expense_requests.id", ondelete="RESTRICT"), nullable=False), sa.Column("event_type", sa.String(40), nullable=False), sa.Column("actor_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("message", sa.Text()), sa.Column("correlation_id", sa.String(100), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("event_type", "correlation_id", name="uq_expense_event_idempotency"))
    op.create_table("expenses", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("expense_number", sa.String(40), nullable=False, unique=True), sa.Column("expense_request_id", sa.Integer(), sa.ForeignKey("expense_requests.id", ondelete="RESTRICT"), nullable=False, unique=True), sa.Column("business_day_id", sa.Integer(), sa.ForeignKey("business_days.id", ondelete="RESTRICT"), nullable=False), sa.Column("requester_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("category_id", sa.Integer(), sa.ForeignKey("expense_categories.id", ondelete="RESTRICT"), nullable=False), sa.Column("amount_minor", sa.BigInteger(), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("payment_source", sa.String(20), nullable=False), sa.Column("reason", sa.Text(), nullable=False), sa.Column("status", sa.String(16), nullable=False, server_default="POSTED"), sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False), sa.Column("posted_by_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("reversed_at", sa.DateTime(timezone=True)), sa.Column("reversed_by_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="RESTRICT")), sa.Column("reversal_reason", sa.Text()), sa.CheckConstraint("amount_minor > 0", name="ck_expense_amount"), sa.CheckConstraint("currency IN ('KHR','USD')", name="ck_expense_currency"), sa.CheckConstraint("payment_source IN ('KHR_CASH','USD_CASH','ABA_KHQR')", name="ck_expense_source"), sa.CheckConstraint("status IN ('POSTED','REVERSED')", name="ck_expense_status"))
    op.create_table("expense_corrections", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("original_expense_id", sa.Integer(), sa.ForeignKey("expenses.id", ondelete="RESTRICT"), nullable=False, unique=True), sa.Column("reason", sa.Text(), nullable=False), sa.Column("actor_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("notification_outbox", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("recipient_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("notification_type", sa.String(50), nullable=False), sa.Column("entity_type", sa.String(40), nullable=False), sa.Column("entity_id", sa.String(80), nullable=False), sa.Column("message", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("sent_at", sa.DateTime(timezone=True)), sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"))


def downgrade() -> None:
    op.drop_table("notification_outbox")
    op.drop_table("expense_corrections")
    op.drop_table("expenses")
    op.drop_table("expense_approval_events")
    op.drop_table("expense_attachments")
    op.drop_table("expense_requests")
    op.drop_table("expense_limits")
    op.drop_table("expense_categories")
